export  const UserData = [
  {
    id: 1,
    firstName: "محمد",
    lastName: "احمدی",
    birthDate: Date.parse("March 21, 1994"),
    job: "برنامه نویس",
    deposit: 200000,
    city: "تهران",
    description: "محمد یک برنامه نویس است",
    img: "./ahmadi.jpg",
  },
  {
    id: 2,
    firstName: "مریم",
    lastName: "فرهادی",
    birthDate: Date.parse("March 21, 1998"),
    job: " طراح گرافیک",
    deposit: 150000,
    city: "شیراز",
    description: "مریم یک دانشجو است",
    img: "./farhadi.jpg",
  },
  {
    id: 3,
    firstName: "علی",
    lastName: "جمالی",
    birthDate: Date.parse("March 21, 1985"),
    deposit: 500000,
    job: " پزشک ",
    city: "اصفهان",
    description: "علی یک پزشک است",
    img: "./jamali.jpg",
  },
  {
    id: 4,
    firstName: "احمد",
    lastName: "مطهری",
    birthDate: Date.parse("March 21, 1978"),
    deposit: 630000,
    job: " برقکار ",
    city: "خوزستان",
    description: "احمد یک برقکار است",
    img: "./motahari.jpg",
  },
  {
    id: 5,
    firstName: "نگار",
    lastName: "رستمی",
    birthDate: Date.parse("March 21, 1997"),
    deposit: 50000,
    job: " مهندس ",
    city: "البرز",
    description: "نگار یک مهندس است",
    img: "./rostami.jpg",
  },
];
